#ifndef QNETWORKMANAGER_GLOBAL_H
#define QNETWORKMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QNETWORKMANAGER_LIBRARY)
#define QNETWORKMANAGER_EXPORT Q_DECL_EXPORT
#else
#define QNETWORKMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif
